export enum NknClientError {
  RpcRequestFail = 'all rpc request failed',
  ClientClosed = 'use of closed network connection',
  KeyNotInMap = 'key not in map',
  InvalidPayloadType = 'invalid payload type',
  ConnectFailed = 'connect failed',
  NoDestination = 'no destination',
  InvalidDestination = 'invalid destination',
  InvalidPubkeyOrName = 'invalid public key or name',
  InvalidPubkeySize = 'invalid public key size',
  InvalidPubkey = 'invalid public key',
  MessageOversize = 'encoded message is greater than',
  NilWebsocketConn = 'nil websocket connection',
  DecryptFailed = 'decrypt message failed',
  AddrNotAllowed = 'address not allowed',
  CreateClientFailed = 'failed to create client',
  NilClient = 'client is nil',
  NotNanoPay = 'not nano pay transaction',
  WrongRecipient = 'wrong nano pay recipient',
  NanoPayClosed = 'use of closed nano pay claimer',
  InsufficientBalance = 'insufficient balance',
  InvalidAmount = 'invalid amount',
  ExpiredNanoPay = 'nanopay expired',
  ExpiredNanoPayTxn = 'nanopay transaction expired',
  WrongPassword = 'wrong password',
  InvalidWalletVersion = 'invalid wallet version',
  UnencryptedMessage = 'message is unencrypted'
}
